<?php

/******************************************************************************/
/******************************************************************************/

class PBFontAwesome
{
	/**************************************************************************/
	
	function __construct()
	{
		$this->font=array
		(
			array('adjust','042'),
			array('adn','170'),
			array('align-center','037'),
			array('align-justify','039'),
			array('align-left','036'),
			array('align-right','038'),
			array('ambulance','0f9'),
			array('anchor','13d'),
			array('android','17b'),
			array('angellist','209'),
			array('angle-double-down','103'),
			array('angle-double-left','100'),
			array('angle-double-right','101'),
			array('angle-double-up','102'),
			array('angle-down','107'),
			array('angle-left','104'),
			array('angle-right','105'),
			array('angle-up','106'),
			array('apple','179'),
			array('archive','187'),
			array('area-chart','1fe'),
			array('arrow-circle-down','0ab'),
			array('arrow-circle-left','0a8'),
			array('arrow-circle-o-down','01a'),
			array('arrow-circle-o-left','190'),
			array('arrow-circle-o-right','18e'),
			array('arrow-circle-o-up','01b'),
			array('arrow-circle-right','0a9'),
			array('arrow-circle-up','0aa'),
			array('arrow-down','063'),
			array('arrow-left','060'),
			array('arrow-right','061'),
			array('arrow-up','062'),
			array('arrows','047'),
			array('arrows-alt','0b2'),
			array('arrows-h','07e'),
			array('arrows-v','07d'),
			array('asterisk','069'),
			array('at','1fa'),
			array('automobile (alias)','1b9'),
			array('backward','04a'),
			array('ban','05e'),
			array('bank (alias)','19c'),
			array('bar-chart','080'),
			array('bar-chart-o (alias)','080'),
			array('barcode','02a'),
			array('bars','0c9'),
			array('bed','236'),
			array('beer','0fc'),
			array('behance','1b4'),
			array('behance-square','1b5'),
			array('bell','0f3'),
			array('bell-o','0a2'),
			array('bell-slash','1f6'),
			array('bell-slash-o','1f7'),
			array('bicycle','206'),
			array('binoculars','1e5'),
			array('birthday-cake','1fd'),
			array('bitbucket','171'),
			array('bitbucket-square','172'),
			array('bitcoin (alias)','15a'),
			array('bold','032'),
			array('bolt','0e7'),
			array('bomb','1e2'),
			array('book','02d'),
			array('bookmark','02e'),
			array('bookmark-o','097'),
			array('briefcase','0b1'),
			array('btc','15a'),
			array('bug','188'),
			array('building','1ad'),
			array('building-o','0f7'),
			array('bullhorn','0a1'),
			array('bullseye','140'),
			array('bus','207'),
			array('buysellads','20d'),
			array('cab (alias)','1ba'),
			array('calculator','1ec'),
			array('calendar','073'),
			array('calendar-o','133'),
			array('camera','030'),
			array('camera-retro','083'),
			array('car','1b9'),
			array('caret-down','0d7'),
			array('caret-left','0d9'),
			array('caret-right','0da'),
			array('caret-square-o-down','150'),
			array('caret-square-o-left','191'),
			array('caret-square-o-right','152'),
			array('caret-square-o-up','151'),
			array('caret-up','0d8'),
			array('cart-arrow-down','218'),
			array('cart-plus','217'),
			array('cc','20a'),
			array('cc-amex','1f3'),
			array('cc-discover','1f2'),
			array('cc-mastercard','1f1'),
			array('cc-paypal','1f4'),
			array('cc-stripe','1f5'),
			array('cc-visa','1f0'),
			array('certificate','0a3'),
			array('chain (alias)','0c1'),
			array('chain-broken','127'),
			array('check','00c'),
			array('check-circle','058'),
			array('check-circle-o','05d'),
			array('check-square','14a'),
			array('check-square-o','046'),
			array('chevron-circle-down','13a'),
			array('chevron-circle-left','137'),
			array('chevron-circle-right','138'),
			array('chevron-circle-up','139'),
			array('chevron-down','078'),
			array('chevron-left','053'),
			array('chevron-right','054'),
			array('chevron-up','077'),
			array('child','1ae'),
			array('circle','111'),
			array('circle-o','10c'),
			array('circle-o-notch','1ce'),
			array('circle-thin','1db'),
			array('clipboard','0ea'),
			array('clock-o','017'),
			array('close (alias)','00d'),
			array('cloud','0c2'),
			array('cloud-download','0ed'),
			array('cloud-upload','0ee'),
			array('cny (alias)','157'),
			array('code','121'),
			array('code-fork','126'),
			array('codepen','1cb'),
			array('coffee','0f4'),
			array('cog','013'),
			array('cogs','085'),
			array('columns','0db'),
			array('comment','075'),
			array('comment-o','0e5'),
			array('comments','086'),
			array('comments-o','0e6'),
			array('compass','14e'),
			array('compress','066'),
			array('connectdevelop','20e'),
			array('copy (alias)','0c5'),
			array('copyright','1f9'),
			array('credit-card','09d'),
			array('crop','125'),
			array('crosshairs','05b'),
			array('css3','13c'),
			array('cube','1b2'),
			array('cubes','1b3'),
			array('cut (alias)','0c4'),
			array('cutlery','0f5'),
			array('dashboard (alias)','0e4'),
			array('dashcube','210'),
			array('database','1c0'),
			array('dedent (alias)','03b'),
			array('delicious','1a5'),
			array('desktop','108'),
			array('deviantart','1bd'),
			array('diamond','219'),
			array('digg','1a6'),
			array('dollar (alias)','155'),
			array('dot-circle-o','192'),
			array('download','019'),
			array('dribbble','17d'),
			array('dropbox','16b'),
			array('drupal','1a9'),
			array('edit (alias)','044'),
			array('eject','052'),
			array('ellipsis-h','141'),
			array('ellipsis-v','142'),
			array('empire','1d1'),
			array('envelope','0e0'),
			array('envelope-o','003'),
			array('envelope-square','199'),
			array('eraser','12d'),
			array('eur','153'),
			array('euro (alias)','153'),
			array('exchange','0ec'),
			array('exclamation','12a'),
			array('exclamation-circle','06a'),
			array('exclamation-triangle','071'),
			array('expand','065'),
			array('external-link','08e'),
			array('external-link-square','14c'),
			array('eye','06e'),
			array('eye-slash','070'),
			array('eyedropper','1fb'),
			array('facebook','09a'),
			array('facebook-f (alias)','09a'),
			array('facebook-official','230'),
			array('facebook-square','082'),
			array('fast-backward','049'),
			array('fast-forward','050'),
			array('fax','1ac'),
			array('female','182'),
			array('fighter-jet','0fb'),
			array('file','15b'),
			array('file-archive-o','1c6'),
			array('file-audio-o','1c7'),
			array('file-code-o','1c9'),
			array('file-excel-o','1c3'),
			array('file-image-o','1c5'),
			array('file-movie-o (alias)','1c8'),
			array('file-o','016'),
			array('file-pdf-o','1c1'),
			array('file-photo-o (alias)','1c5'),
			array('file-picture-o (alias)','1c5'),
			array('file-powerpoint-o','1c4'),
			array('file-sound-o (alias)','1c7'),
			array('file-text','15c'),
			array('file-text-o','0f6'),
			array('file-video-o','1c8'),
			array('file-word-o','1c2'),
			array('file-zip-o (alias)','1c6'),
			array('files-o','0c5'),
			array('film','008'),
			array('filter','0b0'),
			array('fire','06d'),
			array('fire-extinguisher','134'),
			array('flag','024'),
			array('flag-checkered','11e'),
			array('flag-o','11d'),
			array('flash (alias)','0e7'),
			array('flask','0c3'),
			array('flickr','16e'),
			array('floppy-o','0c7'),
			array('folder','07b'),
			array('folder-o','114'),
			array('folder-open','07c'),
			array('folder-open-o','115'),
			array('font','031'),
			array('forumbee','211'),
			array('forward','04e'),
			array('foursquare','180'),
			array('frown-o','119'),
			array('futbol-o','1e3'),
			array('gamepad','11b'),
			array('gavel','0e3'),
			array('gbp','154'),
			array('ge (alias)','1d1'),
			array('gear (alias)','013'),
			array('gears (alias)','085'),
			array('genderless (alias)','1db'),
			array('gift','06b'),
			array('git','1d3'),
			array('git-square','1d2'),
			array('github','09b'),
			array('github-alt','113'),
			array('github-square','092'),
			array('gittip (alias)','184'),
			array('glass','000'),
			array('globe','0ac'),
			array('google','1a0'),
			array('google-plus','0d5'),
			array('google-plus-square','0d4'),
			array('google-wallet','1ee'),
			array('graduation-cap','19d'),
			array('gratipay','184'),
			array('group (alias)','0c0'),
			array('h-square','0fd'),
			array('hacker-news','1d4'),
			array('hand-o-down','0a7'),
			array('hand-o-left','0a5'),
			array('hand-o-right','0a4'),
			array('hand-o-up','0a6'),
			array('hdd-o','0a0'),
			array('header','1dc'),
			array('headphones','025'),
			array('heart','004'),
			array('heart-o','08a'),
			array('heartbeat','21e'),
			array('history','1da'),
			array('home','015'),
			array('hospital-o','0f8'),
			array('hotel (alias)','236'),
			array('html5','13b'),
			array('ils','20b'),
			array('image (alias)','03e'),
			array('inbox','01c'),
			array('indent','03c'),
			array('info','129'),
			array('info-circle','05a'),
			array('inr','156'),
			array('instagram','16d'),
			array('institution (alias)','19c'),
			array('ioxhost','208'),
			array('italic','033'),
			array('joomla','1aa'),
			array('jpy','157'),
			array('jsfiddle','1cc'),
			array('key','084'),
			array('keyboard-o','11c'),
			array('krw','159'),
			array('language','1ab'),
			array('laptop','109'),
			array('lastfm','202'),
			array('lastfm-square','203'),
			array('leaf','06c'),
			array('leanpub','212'),
			array('legal (alias)','0e3'),
			array('lemon-o','094'),
			array('level-down','149'),
			array('level-up','148'),
			array('life-bouy (alias)','1cd'),
			array('life-buoy (alias)','1cd'),
			array('life-ring','1cd'),
			array('life-saver (alias)','1cd'),
			array('lightbulb-o','0eb'),
			array('line-chart','201'),
			array('link','0c1'),
			array('linkedin','0e1'),
			array('linkedin-square','08c'),
			array('linux','17c'),
			array('list','03a'),
			array('list-alt','022'),
			array('list-ol','0cb'),
			array('list-ul','0ca'),
			array('location-arrow','124'),
			array('lock','023'),
			array('long-arrow-down','175'),
			array('long-arrow-left','177'),
			array('long-arrow-right','178'),
			array('long-arrow-up','176'),
			array('magic','0d0'),
			array('magnet','076'),
			array('mail-forward (alias)','064'),
			array('mail-reply (alias)','112'),
			array('mail-reply-all (alias)','122'),
			array('male','183'),
			array('map-marker','041'),
			array('mars','222'),
			array('mars-double','227'),
			array('mars-stroke','229'),
			array('mars-stroke-h','22b'),
			array('mars-stroke-v','22a'),
			array('maxcdn','136'),
			array('meanpath','20c'),
			array('medium','23a'),
			array('medkit','0fa'),
			array('meh-o','11a'),
			array('mercury','223'),
			array('microphone','130'),
			array('microphone-slash','131'),
			array('minus','068'),
			array('minus-circle','056'),
			array('minus-square','146'),
			array('minus-square-o','147'),
			array('mobile','10b'),
			array('mobile-phone (alias)','10b'),
			array('money','0d6'),
			array('moon-o','186'),
			array('mortar-board (alias)','19d'),
			array('motorcycle','21c'),
			array('music','001'),
			array('navicon (alias)','0c9'),
			array('neuter','22c'),
			array('newspaper-o','1ea'),
			array('openid','19b'),
			array('outdent','03b'),
			array('pagelines','18c'),
			array('paint-brush','1fc'),
			array('paper-plane','1d8'),
			array('paper-plane-o','1d9'),
			array('paperclip','0c6'),
			array('paragraph','1dd'),
			array('paste (alias)','0ea'),
			array('pause','04c'),
			array('paw','1b0'),
			array('paypal','1ed'),
			array('pencil','040'),
			array('pencil-square','14b'),
			array('pencil-square-o','044'),
			array('phone','095'),
			array('phone-square','098'),
			array('photo (alias)','03e'),
			array('picture-o','03e'),
			array('pie-chart','200'),
			array('pied-piper','1a7'),
			array('pied-piper-alt','1a8'),
			array('pinterest','0d2'),
			array('pinterest-p','231'),
			array('pinterest-square','0d3'),
			array('plane','072'),
			array('play','04b'),
			array('play-circle','144'),
			array('play-circle-o','01d'),
			array('plug','1e6'),
			array('plus','067'),
			array('plus-circle','055'),
			array('plus-square','0fe'),
			array('plus-square-o','196'),
			array('power-off','011'),
			array('print','02f'),
			array('puzzle-piece','12e'),
			array('qq','1d6'),
			array('qrcode','029'),
			array('question','128'),
			array('question-circle','059'),
			array('quote-left','10d'),
			array('quote-right','10e'),
			array('ra (alias)','1d0'),
			array('random','074'),
			array('rebel','1d0'),
			array('recycle','1b8'),
			array('reddit','1a1'),
			array('reddit-square','1a2'),
			array('refresh','021'),
			array('remove (alias)','00d'),
			array('renren','18b'),
			array('reorder (alias)','0c9'),
			array('repeat','01e'),
			array('reply','112'),
			array('reply-all','122'),
			array('retweet','079'),
			array('rmb (alias)','157'),
			array('road','018'),
			array('rocket','135'),
			array('rotate-left (alias)','0e2'),
			array('rotate-right (alias)','01e'),
			array('rouble (alias)','158'),
			array('rss','09e'),
			array('rss-square','143'),
			array('rub','158'),
			array('ruble (alias)','158'),
			array('rupee (alias)','156'),
			array('save (alias)','0c7'),
			array('scissors','0c4'),
			array('search','002'),
			array('search-minus','010'),
			array('search-plus','00e'),
			array('sellsy','213'),
			array('send (alias)','1d8'),
			array('send-o (alias)','1d9'),
			array('server','233'),
			array('share','064'),
			array('share-alt','1e0'),
			array('share-alt-square','1e1'),
			array('share-square','14d'),
			array('share-square-o','045'),
			array('shekel (alias)','20b'),
			array('sheqel (alias)','20b'),
			array('shield','132'),
			array('ship','21a'),
			array('shirtsinbulk','214'),
			array('shopping-cart','07a'),
			array('sign-in','090'),
			array('sign-out','08b'),
			array('signal','012'),
			array('simplybuilt','215'),
			array('sitemap','0e8'),
			array('skyatlas','216'),
			array('skype','17e'),
			array('slack','198'),
			array('sliders','1de'),
			array('slideshare','1e7'),
			array('smile-o','118'),
			array('soccer-ball-o (alias)','1e3'),
			array('sort','0dc'),
			array('sort-alpha-asc','15d'),
			array('sort-alpha-desc','15e'),
			array('sort-amount-asc','160'),
			array('sort-amount-desc','161'),
			array('sort-asc','0de'),
			array('sort-desc','0dd'),
			array('sort-down (alias)','0dd'),
			array('sort-numeric-asc','162'),
			array('sort-numeric-desc','163'),
			array('sort-up (alias)','0de'),
			array('soundcloud','1be'),
			array('space-shuttle','197'),
			array('spinner','110'),
			array('spoon','1b1'),
			array('spotify','1bc'),
			array('square','0c8'),
			array('square-o','096'),
			array('stack-exchange','18d'),
			array('stack-overflow','16c'),
			array('star','005'),
			array('star-half','089'),
			array('star-half-empty (alias)','123'),
			array('star-half-full (alias)','123'),
			array('star-half-o','123'),
			array('star-o','006'),
			array('steam','1b6'),
			array('steam-square','1b7'),
			array('step-backward','048'),
			array('step-forward','051'),
			array('stethoscope','0f1'),
			array('stop','04d'),
			array('street-view','21d'),
			array('strikethrough','0cc'),
			array('stumbleupon','1a4'),
			array('stumbleupon-circle','1a3'),
			array('subscript','12c'),
			array('subway','239'),
			array('suitcase','0f2'),
			array('sun-o','185'),
			array('superscript','12b'),
			array('support (alias)','1cd'),
			array('table','0ce'),
			array('tablet','10a'),
			array('tachometer','0e4'),
			array('tag','02b'),
			array('tags','02c'),
			array('tasks','0ae'),
			array('taxi','1ba'),
			array('tencent-weibo','1d5'),
			array('terminal','120'),
			array('text-height','034'),
			array('text-width','035'),
			array('th','00a'),
			array('th-large','009'),
			array('th-list','00b'),
			array('thumb-tack','08d'),
			array('thumbs-down','165'),
			array('thumbs-o-down','088'),
			array('thumbs-o-up','087'),
			array('thumbs-up','164'),
			array('ticket','145'),
			array('times','00d'),
			array('times-circle','057'),
			array('times-circle-o','05c'),
			array('tint','043'),
			array('toggle-down (alias)','150'),
			array('toggle-left (alias)','191'),
			array('toggle-off','204'),
			array('toggle-on','205'),
			array('toggle-right (alias)','152'),
			array('toggle-up (alias)','151'),
			array('train','238'),
			array('transgender','224'),
			array('transgender-alt','225'),
			array('trash','1f8'),
			array('trash-o','014'),
			array('tree','1bb'),
			array('trello','181'),
			array('trophy','091'),
			array('truck','0d1'),
			array('try','195'),
			array('tty','1e4'),
			array('tumblr','173'),
			array('tumblr-square','174'),
			array('turkish-lira (alias)','195'),
			array('twitch','1e8'),
			array('twitter','099'),
			array('twitter-square','081'),
			array('umbrella','0e9'),
			array('underline','0cd'),
			array('undo','0e2'),
			array('university','19c'),
			array('unlink (alias)','127'),
			array('unlock','09c'),
			array('unlock-alt','13e'),
			array('unsorted (alias)','0dc'),
			array('upload','093'),
			array('usd','155'),
			array('user','007'),
			array('user-md','0f0'),
			array('user-plus','234'),
			array('user-secret','21b'),
			array('user-times','235'),
			array('users','0c0'),
			array('venus','221'),
			array('venus-double','226'),
			array('venus-mars','228'),
			array('viacoin','237'),
			array('video-camera','03d'),
			array('vimeo-square','194'),
			array('vine','1ca'),
			array('vk','189'),
			array('volume-down','027'),
			array('volume-off','026'),
			array('volume-up','028'),
			array('warning (alias)','071'),
			array('wechat (alias)','1d7'),
			array('weibo','18a'),
			array('weixin','1d7'),
			array('whatsapp','232'),
			array('wheelchair','193'),
			array('wifi','1eb'),
			array('windows','17a'),
			array('won (alias)','159'),
			array('wordpress','19a'),
			array('wrench','0ad'),
			array('xing','168'),
			array('xing-square','169'),
			array('yahoo','19e'),
			array('yelp','1e9'),
			array('yen (alias)','157'),
			array('youtube','167'),
			array('youtube-play','16a'),
			array('youtube-square','166')		
		);
	}
	
	/**************************************************************************/
	
	function getFontByString()
	{
		$query=$_GET['query'];
		
		$data=array();
		$result=array();
		
		foreach($this->font as $fontData)
		{
			if(preg_match('/^'.preg_quote($query,'/').'/i',$fontData[0],$result))
			{
				$data[]=array('value'=>$fontData[0],'label'=>'<i class="fa fa-'.esc_attr($fontData[0]).'"></i><span>'.esc_html('fa-'.$fontData[0]).'</span>');
				if(count($data)==10) break;
			}
		}
		
		echo json_encode($data);
		exit;		
	}
	
	/**************************************************************************/
}

/******************************************************************************/
/******************************************************************************/


